BART_API_BASE_URL = 'http://api.bart.gov/api/%s'
# http://api.bart.gov/docs/overview/index.aspx
BART_API_RESOURCES = {
    'advisories' : 'bsa.aspx', # BART service advisories
    'realtime_estimates' : 'etd.aspx', # estimated time of departure
    'route_information' : 'route.aspx',
    'schedule_information' : 'sched.aspx',
    'station_information' : 'stn.aspx',
    'version_information' : 'version.aspx',
}

# station abbreviations
# http://api.bart.gov/docs/overview/abbrev.aspx
BART_STATION_ABBREVIATIONS = {
    '12th' : '12th St. Oakland City Center',
    '16th' : '16th St. Mission (SF)',
    '19th' : '19th St. Oakland',
    '24th' : '24th St. Mission (SF)',
    'ashb' : 'Ashby (Berkeley)',
    'balb' : 'Balboa Park (SF)',
    'bayf' : 'Bay Fair (San Leandro)',
    'cast' : 'Castro Valley',
    'civc' : 'Civic Center (SF)',
    'cols' : 'Coliseum',
    'colm' : 'Colma',
    'conc' : 'Concord',
    'daly' : 'Daly City',
    'dbrk' : 'Downtown Berkeley',
    'dubl' : 'Dublin/Pleasanton',
    'deln' : 'El Cerrito del Norte',
    'plza' : 'El Cerrito Plaza',
    'embr' : 'Embarcadero (SF)',
    'frmt' : 'Fremont',
    'ftvl' : 'Fruitvale (Oakland)',
    'glen' : 'Glen Park (SF)',
    'hayw' : 'Hayward',
    'lafy' : 'Lafayette',
    'lake' : 'Lake Merritt (Oakland)',
    'mcar' : 'MacArthur (Oakland)',
    'mlbr' : 'Millbrae',
    'mont' : 'Montgomery St. (SF)',
    'nbrk' : 'North Berkeley',
    'ncon' : 'North Concord/Martinez',
    'oakl' : 'Oakland International Airport',
    'orin' : 'Orinda',
    'pitt' : 'Pittsburg/Bay Point',
    'phil' : 'Pleasant Hill',
    'powl' : 'Powell St. (SF)',
    'rich' : 'Richmond',
    'rock' : 'Rockridge (Oakland)',
    'sbrn' : 'San Bruno',
    'sfia' : 'San Francisco International Airport',
    'sanl' : 'San Leandro',
    'shay' : 'South Hayward',
    'ssan' : 'South San Francisco',
    'ucty' : 'Union City',
    'warm' : 'Warm Springs/South Fremont',
    'wcrk' : 'Walnut Creek',
    'wdub' : 'West Dublin',
    'woak' : 'West Oakland',
}
