HTK_FEEDBACK_EMAIL_SUBJECT = 'New feedback from Hacktoolkit form'


FEEDBACK_REQUEST_TYPE_FEATURE = 'feature_request'
FEEDBACK_REQUEST_TYPE_BUG = 'bug_report'
FEEDBACK_REQUEST_TYPE_CONTENT = 'content_issue'
FEEDBACK_REQUEST_TYPE_SUPPORT = 'support_question'
FEEDBACK_REQUEST_TYPE_GENERAL = 'general_feedback'

FEEDBACK_REQUEST_TYPE_CHOICES = (
    (FEEDBACK_REQUEST_TYPE_FEATURE, 'Feature request'),
    (FEEDBACK_REQUEST_TYPE_BUG, 'Bug report'),
    (FEEDBACK_REQUEST_TYPE_CONTENT, 'Content issue'),
    (FEEDBACK_REQUEST_TYPE_SUPPORT, 'Support question'),
    (FEEDBACK_REQUEST_TYPE_GENERAL, 'General feedback'),
)

FEEDBACK_VISIBILITY_PUBLIC = 'public'
FEEDBACK_VISIBILITY_UNLISTED = 'unlisted'
FEEDBACK_VISIBILITY_PRIVATE = 'private'

FEEDBACK_VISIBILITY_CHOICES = (
    (FEEDBACK_VISIBILITY_PUBLIC, 'Public'),
    (FEEDBACK_VISIBILITY_UNLISTED, 'Unlisted'),
    (FEEDBACK_VISIBILITY_PRIVATE, 'Private'),
)

FEEDBACK_STATUS_NEW = 'new'
FEEDBACK_STATUS_UNDER_REVIEW = 'under_review'
FEEDBACK_STATUS_PLANNED = 'planned'
FEEDBACK_STATUS_IN_PROGRESS = 'in_progress'
FEEDBACK_STATUS_SHIPPED = 'shipped'
FEEDBACK_STATUS_DECLINED = 'declined'
FEEDBACK_STATUS_MERGED = 'merged'


FEEDBACK_VOTE_UP = 1
FEEDBACK_VOTE_DOWN = -1

FEEDBACK_VOTE_CHOICES = (
    (FEEDBACK_VOTE_UP, 'Upvote'),
    (FEEDBACK_VOTE_DOWN, 'Downvote'),
)

FEEDBACK_STATUS_CHOICES = (
    (FEEDBACK_STATUS_NEW, 'New'),
    (FEEDBACK_STATUS_UNDER_REVIEW, 'Under review'),
    (FEEDBACK_STATUS_PLANNED, 'Planned'),
    (FEEDBACK_STATUS_IN_PROGRESS, 'In progress'),
    (FEEDBACK_STATUS_SHIPPED, 'Shipped'),
    (FEEDBACK_STATUS_DECLINED, 'Declined'),
    (FEEDBACK_STATUS_MERGED, 'Merged'),
)

