HTK_BIBLE_BOOK_MODEL = 'bible.BibleBook'
HTK_BIBLE_CHAPTER_MODEL = 'bible.BibleChapter'
HTK_BIBLE_VERSE_MODEL = 'bible.BibleVerse'
HTK_BIBLE_PASSAGE_MODEL = 'bible.BiblePassage'
HTK_BIBLE_NASB_VERSE_MODEL = 'bible.NASBVerse'

HTK_BIBLE_TRANSLATIONS_MAP = {
    'NASB': HTK_BIBLE_NASB_VERSE_MODEL,
}
