HTK_STRIPE_LIVE_MODE = True

HTK_STRIPE_EVENT_HANDLERS = {
}

HTK_STRIPE_LOG_UNHANDLED_EVENTS = True
HTK_STRIPE_LOG_TEST_MODE_EVENTS = True
HTK_STRIPE_EVENT_LOGGER = 'rollbar'

HTK_STRIPE_CUSTOMER_HOLDER_RELATED_NAME = 'customer'
