HTK_COMPANY_EMAIL_DOMAINS = ()
HTK_COMPANY_OFFICER_EMAILS = ()
HTK_COMPANY_EMPLOYEE_EMAILS = ()

HTK_EMULATE_USER_COOKIE_EXPIRATION_MINUTES = 15

# See: `htk.admintools.dataclasses.TodosConfig`
HTK_ADMINTOOLS_TODOS_CONFIGS = []
