// This file is generated by npm run build:icons

export type IconName =
    | 'dashboard'
    | 'double-caret-down'
    | 'double-caret-left'
    | 'double-caret-right'
    | 'double-caret-up'
    | 'hammer'
    | 'logout'
    | 'moon'
    | 'notebook'
    | 'screen'
    | 'sun'
    | 'user'
    | 'users';
