FULLCONTACT_API_BASE_URL = 'https://api.fullcontact.com/v2'

FULLCONTACT_API_RESOURCES = {
    'batch' : '/batch.json',
    'person' : '/person.json',
}

FULLCONTACT_SOCIAL_NETWORK_TYPES = {
    'aboutme' : 'About.me',
    'academiaedu' : 'Academia.edu',
    'amplify' : 'Amplify',
    'angellist' : 'AngelList',
    'aolchat' : 'Aol Chat',
    'bandcamp' : 'Bandcamp',
    'bebo' : 'Bebo',
    'behance' : 'Behance',
    'bitbucket' : 'BitBucket',
    'blipfm' : 'BlipFM',
    'blippy' : 'Blippy',
    'blogger' : 'Blogger',
    'crunchbase' : 'Crunchbase',
    'dandyid' : 'DandyId',
    'delicious' : 'Delicious',
    'deviantart' : 'Deviant Art',
    'digg' : 'Digg',
    'diigo' : 'Diigo',
    'disqus' : 'Disqus',
    'doyoubuzz' : 'Do You Buzz',
    'dribble' : 'Dribbble',
    'econsultancy' : 'eConsultancy',
    'facebook' : 'Facebook',
    'facebookchat' : 'Facebook Chat',
    'flavorsme' : 'Flavors.me',
    'flickr' : 'Flickr',
    'foursquare' : 'FourSquare',
    'friendfeed' : 'FriendFeed',
    'friendster' : 'Friendster',
    'fullcontact' : 'FullContact',
    'gdgt' : 'gdgt',
    'getglue' : 'Get Glue',
    'getsatisfaction' : 'Get Satisfaction',
    'gist' : 'Gist',
    'github' : 'GitHub',
    'googleprofile' : 'Google Profile',
    'googleplus' : 'Google Plus',
    'google' : 'Google Plus',
    'goodreads' : 'Good Reads',
    'gravatar' : 'Gravatar',
    'gtalkchat' : 'GTalk',
    'hackernews' : 'Hacker News',
    'hi5' : 'Hi5',
    'hunch' : 'Hunch',
    'hypemachine' : 'HypeMachine',
    'hyves' : 'Hyves',
    'icqchat' : 'ICQ',
    'identica' : 'Identi.ca',
    'imdb' : 'IMDB',
    'intensedebate' : 'Intense Debate',
    'ircchat' : 'IRC',
    'klout' : 'Klout',
    'lanyrd' : 'Lanyrd',
    'lastfm' : 'Last.FM',
    'linkedin' : 'LinkedIn',
    'livejournal' : 'LiveJournal',
    'meadiciona' : 'Meadiciona',
    'meetup' : 'Meetup',
    'mixcloud' : 'Mixcloud',
    'mixi' : 'Mixi',
    'myspace' : 'MySpace',
    'ohloh' : 'Ohloh',
    'orkut' : 'Orkut',
    'other' : 'Other',
    'pandora' : 'Pandora',
    'picasa' : 'Picasa',
    'pinboard' : 'Pin Board',
    'pinterest' : 'Pinterest',
    'plancast' : 'Plancast',
    'plaxo' : 'Plaxo',
    'plurk' : 'Plurk',
    'qik' : 'Qik',
    'quora' : 'Quora',
    'reddit' : 'Reddit',
    'renren' : 'Ren Ren',
    'reverbnation' : 'Reverb Nation',
    'scribd' : 'Scribd',
    'shelfari' : 'Shelfari',
    'skype' : 'Skype',
    'slideshare' : 'SlideShare',
    'smugmug' : 'Smug Mug',
    'soundcloud' : 'Sound Cloud',
    'stackexchange' : 'StackExchange',
    'stackoverflow' : 'StackOverflow',
    'steam' : 'Steam',
    'stumbleupon' : 'Stumble Upon',
    'tagged' : 'Tagged',
    'tripit' : 'Tripit',
    'tumblr' : 'Tumblr',
    'twitter' : 'Twitter',
    'typepad' : 'Type Pad',
    'vimeo' : 'Vimeo',
    'vk' : 'VK',
    'weibo' : 'Weibo',
    'wordpress' : 'WordPress.com',
    'wordpress' : 'WordPress.org',
    'xing' : 'Xing',
    'yelp' : 'Yelp',
    'youtube' : 'YouTube',
}
