HTK_ORGANIZATION_MODEL = 'organizations.Organization'
HTK_ORGANIZATION_MEMBER_MODEL = 'organizations.OrganizationMember'
HTK_ORGANIZATION_INVITATION_MODEL = 'organizations.OrganizationInvitation'
HTK_ORGANIZATION_TEAM_MODEL = 'organizations.OrganizationTeam'
HTK_ORGANIZATION_TEAM_MEMBER_MODEL = 'organizations.OrganizationTeamMember'
