# Generated by Django 5.2.15 on 2026-07-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('feature_request', 'Feature request'), ('bug_report', 'Bug report'), ('content_issue', 'Content issue'), ('support_question', 'Support question'), ('general_feedback', 'General feedback')], default='feature_request', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('merged', 'Merged')], default='new', max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='private', max_length=24)),
                ('source_uri', models.CharField(blank=True, max_length=1024)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=1024)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('votes_count', models.IntegerField(default=0)),
                ('upvotes_count', models.PositiveIntegerField(default=0)),
                ('downvotes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owned_feedback_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='sites.site')),
            ],
            options={
                'verbose_name': 'Feedback request',
                'verbose_name_plural': 'Feedback requests',
                'ordering': ('-votes_count', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackrequest')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='feedback_request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request comment',
                'verbose_name_plural': 'Feedback request comments',
                'ordering': ('created_on',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequestVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedbackrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback request vote',
                'verbose_name_plural': 'Feedback request votes',
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['site', 'status'], name='feedback_fe_site_id_af55aa_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['site', 'request_type'], name='feedback_fe_site_id_a85dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['site', 'visibility'], name='feedback_fe_site_id_ac2a88_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackrequest',
            index=models.Index(fields=['site', 'created_on'], name='feedback_fe_site_id_cc98cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackrequestvote',
            constraint=models.UniqueConstraint(fields=('feedback', 'user'), name='feedback_unique_user_vote'),
        ),
    ]
