REQUEST_HTTP_HEADERS_STANDARD = [
    'HTTP_ACCEPT',
    'HTTP_ACCEPT_ENCODING',
    'HTTP_ACCEPT_LANGUAGE',
    'HTTP_CACHE_CONTROL',
    'HTTP_CONNECTION',
    'HTTP_COOKIE',
    'HTTP_HOST',
    'HTTP_UPGRADE_INSECURE_REQUESTS',
    'HTTP_USER_AGENT',
    'HTTP_REFERER',
]
