# Generated by Django 3.2.15 on 2023-06-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrelaunchSignup',
        ),
    ]
