SOCIAL_AUTH_PARTIAL_PIPELINE_KEY = 'partial_pipeline'

SOCIAL_REGISTRATION_SETTING_MISSING_EMAIL = 'social_registration_setting_missing_email'
SOCIAL_REGISTRATION_SETTING_EMAIL = 'social_registration_setting_email'

SOCIAL_AUTH_FLOW_KEYS = [
    SOCIAL_AUTH_PARTIAL_PIPELINE_KEY,
    SOCIAL_REGISTRATION_SETTING_EMAIL,
    SOCIAL_REGISTRATION_SETTING_MISSING_EMAIL,
]
