HTK_CHANGELOG_FILE_PATH = 'CHANGELOG.md'
HTK_CHANGELOG_SLACK_CHANNEL_RELEASES = '#release-notes'
HTK_CHANGELOG_VIEW_IN_WEB_URL_NAME = None
HTK_CHANGELOG_VIEW_IN_WEB_URL = None

HTK_COMPANY_EMPLOYEE_GITHUB_USERNAMES_MAP = {}
